# Generated by Django 5.1.5 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_inmobiliaria_profile_inmobiliaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmobiliaria',
            old_name='texto_contractual',
            new_name='texto_contractual_captacion',
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='cedula_firma_autorizada',
            field=models.CharField(blank=True, help_text='Cédula o documento de identidad', max_length=30),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='firma_autorizada',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_inmobiliarias/'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='nombre_firma_autorizada',
            field=models.CharField(blank=True, help_text='Nombre del representante autorizado que firma', max_length=150),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_entrega',
            field=models.TextField(default='Texto contractual por defecto...'),
        ),
    ]
