# Generated by Django 5.1.5 on 2025-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_texto_contractual_inmobiliaria_texto_contractual_captacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmobiliaria',
            name='texto_contractual_captacion',
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_captacion_renta',
            field=models.TextField(default='Texto contractual de captación para renta por defecto...'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_captacion_venta',
            field=models.TextField(default='Texto contractual de captación para venta por defecto...'),
        ),
    ]
