# Generated by Django 5.1.5 on 2025-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0003_alter_formulariocaptacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocaptacion',
            name='valor_renta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocaptacion',
            name='valor_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
