# Generated by Django 5.1.5 on 2025-02-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0006_alter_formulariocaptacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_campo', models.CharField(choices=[('NU', 'Número'), ('TE', 'Texto'), ('SN', 'Si/No')], max_length=2)),
                ('tipo_detalle', models.CharField(choices=[('GN', 'General'), ('IN', 'Interior'), ('EX', 'Exterior')], max_length=2)),
                ('clase_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.tipopropiedad')),
            ],
            options={
                'verbose_name': 'Detalle de Propiedad',
                'verbose_name_plural': 'Detalles de Propiedad',
            },
        ),
    ]
