# Generated by Django 5.1.5 on 2025-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0007_detallepropiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepropiedad',
            name='clase_propiedad',
        ),
        migrations.AddField(
            model_name='detallepropiedad',
            name='clase_propiedad',
            field=models.ManyToManyField(blank=True, to='inventarioapp.tipopropiedad'),
        ),
    ]
