# Generated by Django 5.1.5 on 2025-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0015_rename_inventarioa_created_b5c69e_idx_inventarioa_created_ce328a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioentrega',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioentrega',
            name='is_firmado',
            field=models.BooleanField(default=False),
        ),
    ]
