# Generated by Django 5.1.5 on 2025-05-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0017_formularioentrega_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioentrega',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='inventarioapp.propiedad'),
        ),
    ]
