# Generated by Django 5.1.5 on 2025-05-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0019_remove_formularioentrega_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección de Captación',
                'verbose_name_plural': 'Secciones de Captación',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='altdetallesgenerales',
            name='formulario_captacion',
        ),
        migrations.RemoveField(
            model_name='altdetallesinteriores',
            name='formulario_captacion',
        ),
        migrations.RemoveField(
            model_name='detallecaptacion',
            name='detalle_propiedad',
        ),
        migrations.RemoveField(
            model_name='detallecaptacion',
            name='formulario_captacion',
        ),
        migrations.RemoveField(
            model_name='detallepropiedad',
            name='clase_propiedad',
        ),
        migrations.RemoveField(
            model_name='formulariocaptacion',
            name='propiedad',
        ),
        migrations.CreateModel(
            name='CampoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Sí/No')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatorio', models.BooleanField(default=False)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='inventarioapp.seccioncaptacion')),
            ],
            options={
                'verbose_name': 'Campo de Captación',
                'verbose_name_plural': 'Campos de Captación',
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='AltDetallesExteriores',
        ),
        migrations.DeleteModel(
            name='AltDetallesGenerales',
        ),
        migrations.DeleteModel(
            name='AltDetallesInteriores',
        ),
        migrations.DeleteModel(
            name='DetalleCaptacion',
        ),
        migrations.DeleteModel(
            name='DetallePropiedad',
        ),
        migrations.DeleteModel(
            name='FormularioCaptacion',
        ),
    ]
