# Generated by Django 5.1.5 on 2025-05-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0020_seccioncaptacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas_captacion/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('propiedad_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaciones', to='inventarioapp.propiedadcliente')),
            ],
            options={
                'verbose_name': 'Formulario de Captación',
                'verbose_name_plural': 'Formularios de Captación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.campocaptacion')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='inventarioapp.formulariocaptacion')),
            ],
            options={
                'verbose_name': 'Valor de Campo de Captación',
                'verbose_name_plural': 'Valores de Campos de Captación',
                'unique_together': {('formulario', 'campo')},
            },
        ),
    ]
