# Generated by Django 5.1.5 on 2025-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0022_propiedadcliente_unique_cliente_propiedad_relacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioentrega',
            name='tipo_captacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], default='venta', max_length=10),
            preserve_default=False,
        ),
    ]
