# Generated by Django 5.1.5 on 2025-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0024_remove_formularioentrega_tipo_captacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
