# Generated by Django 5.1.5 on 2025-02-13 21:52

import django.db.models.deletion
import inventarioAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[inventarioAPP.models.only_int])),
                ('direccion_correspondiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad_propiedad', to='inventarioAPP.ciudad')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('PR', 'Propietario'), ('AP', 'Apoderado'), ('AR', 'Arrendatario')], default='PR', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='clientes',
            field=models.ManyToManyField(related_name='clientes_propiedad', through='inventarioAPP.PropiedadCliente', to='inventarioAPP.cliente'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propiedad_tipo', to='inventarioAPP.tipopropiedad'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['-created'], name='inventarioA_created_b5c69e_idx'),
        ),
    ]
