# Generated by Django 5.1.5 on 2025-02-20 15:38

import django.db.models.deletion
import inventarioapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-created'], 'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='propiedadcliente',
            options={'verbose_name': 'Propiedades y Clientes', 'verbose_name_plural': 'Propiedades y Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tipopropiedad',
            options={'ordering': ['tipo_propiedad'], 'verbose_name': 'Tipo de Propiedades', 'verbose_name_plural': 'Tipos de Propiedades'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[inventarioapp.models.only_int]),
        ),
        migrations.AlterField(
            model_name='propiedadcliente',
            name='relacion',
            field=models.CharField(choices=[('PR', 'Propietario'), ('AP', 'Apoderado'), ('AR', 'Arrendatario')], max_length=2),
        ),
        migrations.CreateModel(
            name='FormularioCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_captacion', models.CharField(choices=[('RE', 'Renta'), ('VE', 'Venta'), ('AM', 'Ambos')], max_length=2)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=13)),
                ('valor_renta', models.DecimalField(decimal_places=2, max_digits=13)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.propiedad')),
            ],
        ),
    ]
