# Generated by Django 5.1.5 on 2025-02-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0002_alter_ciudad_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocaptacion',
            options={'verbose_name': 'Formulario de Captación', 'verbose_name_plural': 'Formularios de Captación'},
        ),
    ]
