# Generated by Django 5.1.5 on 2025-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0005_alter_formulariocaptacion_tipo_captacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocaptacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
