# Generated by Django 5.1.5 on 2025-02-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0008_remove_detallepropiedad_clase_propiedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('detalle_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioAPP.detallepropiedad')),
                ('formulario_captacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioAPP.formulariocaptacion')),
            ],
        ),
    ]
