# Generated by Django 5.1.5 on 2025-02-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0009_detallecaptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecaptacion',
            name='formulario_captacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.formulariocaptacion'),
        ),
    ]
