# Generated by Django 5.1.5 on 2025-03-10 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0010_alter_detallecaptacion_formulario_captacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltFormularioCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_captacion', models.CharField(blank=True, choices=[('RE', 'Renta'), ('VE', 'Venta'), ('AM', 'Ambos')], max_length=2, null=True)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_renta', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.propiedad')),
            ],
            options={
                'verbose_name': 'Formulario de Captación',
                'verbose_name_plural': 'Formularios de Captación',
            },
        ),
        migrations.CreateModel(
            name='AltDetallesInteriores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closets', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('vestier', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('turco', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('jacuzzi', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('zona_de_lavanderia', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('tipo_de_piso', models.CharField(blank=True, max_length=100, null=True)),
                ('sauna', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('patio', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cocina_integral', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('hall_de_alcobas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cuarto_de_servicio', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('deposito', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('estudio', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('comedor_auxiliar', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cocina_tipo_americano', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('tipo_instalacion_de_gas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Instalación de Gas')),
                ('citofono', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Citófono')),
                ('chimenea', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('calentador', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('barra_estilo_americano', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('banio_auxiliar', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Baño Auxiliar')),
                ('balcon', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Balcón')),
                ('amoblado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('alarma', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('aire_acondicionado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('otros_u_observaciones', models.TextField(blank=True, null=True)),
                ('alt_formulario_captacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.altformulariocaptacion')),
            ],
            options={
                'verbose_name': 'Detalles Interiores Formulario de Captación',
            },
        ),
        migrations.CreateModel(
            name='AltDetallesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parqueadero_cubierto', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('parqueaderos', models.IntegerField(blank=True, null=True)),
                ('valor_gravamen', models.BigIntegerField(blank=True, null=True)),
                ('gravamen', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('estado_nuevo_usado', models.CharField(blank=True, choices=[('NU', 'Nuevo'), ('US', 'Usado')], max_length=2, null=True, verbose_name='Nuevo/Usado')),
                ('cantidad_banios', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Baños')),
                ('numero_piso', models.IntegerField(blank=True, null=True, verbose_name='Número de Piso')),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('anios_construido', models.IntegerField(blank=True, null=True, verbose_name='Años Construido')),
                ('valor_administracion', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_habitaciones', models.IntegerField(blank=True, null=True)),
                ('area_privada', models.IntegerField(blank=True, null=True, verbose_name='Área Privada')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Área')),
                ('estrato', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('alt_formulario_captacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.altformulariocaptacion')),
            ],
            options={
                'verbose_name': 'Detalles Generales Formulario de Captación',
            },
        ),
        migrations.CreateModel(
            name='AltDetallesExteriores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jacuzzi', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cancha_multiple', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Cancha Múltiple')),
                ('zona_bbq', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Zona BBQ')),
                ('turco', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('sauna', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('espejo_de_agua', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('vigilancia', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('terraza', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('zona_infantil', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('vista_panoramica', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Vista Panorámica')),
                ('salon_de_juegos', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('sala_de_internet', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('planta_electrica', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Planta Eléctrica')),
                ('parqueadero_visitantes', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cuarto_de_escoltas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('salon_comunal', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('oficina_de_negocios', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('espacio_de_golf', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('circuito_cerrado_de_tv', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Circuito Cerrado de TV')),
                ('cancha_de_tenis', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('jardin', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True, verbose_name='Jardín')),
                ('caldera', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('gimnasio', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('zonas_verdes', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('piscina', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('ascensor', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('conjunto_cerrado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('alt_formulario_captacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.altformulariocaptacion')),
            ],
            options={
                'verbose_name': 'Detalles Exteriores Formulario de Captación',
            },
        ),
    ]
