# Generated by Django 5.1.5 on 2025-05-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0014_formularioentrega_ambienteentrega_itembase_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propiedad',
            new_name='inventarioa_created_ce328a_idx',
            old_name='inventarioA_created_b5c69e_idx',
        ),
        migrations.AlterField(
            model_name='altdetallesexteriores',
            name='formulario_captacion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.formulariocaptacion'),
        ),
        migrations.AlterField(
            model_name='altdetallesgenerales',
            name='formulario_captacion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.formulariocaptacion'),
        ),
        migrations.AlterField(
            model_name='altdetallesinteriores',
            name='formulario_captacion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.formulariocaptacion'),
        ),
        migrations.AlterField(
            model_name='ambienteentrega',
            name='formulario_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='inventarioapp.formularioentrega'),
        ),
        migrations.AlterField(
            model_name='detallecaptacion',
            name='detalle_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioapp.detallepropiedad'),
        ),
        migrations.AlterField(
            model_name='detallecaptacion',
            name='formulario_captacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.formulariocaptacion'),
        ),
        migrations.AlterField(
            model_name='detallepropiedad',
            name='clase_propiedad',
            field=models.ManyToManyField(blank=True, to='inventarioapp.tipopropiedad'),
        ),
        migrations.AlterField(
            model_name='formulariocaptacion',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.propiedad'),
        ),
        migrations.AlterField(
            model_name='formularioentrega',
            name='propiedad_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.propiedadcliente'),
        ),
        migrations.AlterField(
            model_name='itementrega',
            name='ambiente_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarioapp.ambienteentrega'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad_propiedad', to='inventarioapp.ciudad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='clientes',
            field=models.ManyToManyField(related_name='clientes_propiedad', through='inventarioapp.PropiedadCliente', to='inventarioapp.cliente'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propiedad_tipo', to='inventarioapp.tipopropiedad'),
        ),
        migrations.AlterField(
            model_name='propiedadcliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.cliente'),
        ),
        migrations.AlterField(
            model_name='propiedadcliente',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.propiedad'),
        ),
    ]
