# Generated by Django 5.1.5 on 2025-05-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0016_formularioentrega_fecha_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioentrega',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='inventarioapp.propiedad'),
        ),
    ]
