# Generated by Django 5.1.5 on 2025-05-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0018_alter_formularioentrega_propiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioentrega',
            name='propiedad',
        ),
    ]
