# Generated by Django 5.1.5 on 2025-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0021_formulariocaptacion_valorcampocaptacion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propiedadcliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'propiedad', 'relacion'), name='unique_cliente_propiedad_relacion'),
        ),
    ]
